### ISSUE TITLE
Error when training with shapenet_car

### ISSUE THREAD

**Issue by LiZimo** [TonythePlaneswalker/pcn#1]
Thanks for releasing your code!  

I get this error message when attempting to train:

```
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    train(args)
  File "train.py", line 42, in train
    model = model_module.Model(inputs, gt, alpha)
  File "/home/zimo/Documents/pcn/models/pcn_cd.py", line 10, in __init__
    self.features = self.create_encoder(inputs)
  File "/home/zimo/Documents/pcn/models/pcn_cd.py", line 19, in create_encoder
    features = mlp_conv(inputs, [128, 256])
  File "/home/zimo/Documents/pcn/tf_util.py", line 26, in mlp_conv
    normalizer_params=bn_params
  File "/home/zimo/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/zimo/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1154, in convolution2d
    conv_dims=2)
  File "/home/zimo/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/zimo/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1025, in convolution
    (conv_dims + 2, input_rank))
ValueError: Convolution expects input with rank 4, got 3
```

It seems "inputs" has rank 3 with the default settings:

```
>>> inputs.get_shape()
TensorShape([Dimension(32), Dimension(2048), Dimension(3)])
```

However, the call to conv2d wants the input rank to be 2 (the dimension of convolution) + input_rank.  I checked the source code for 1.4 as well - it is the same with respect to checking this condition. I did not want to download the entire training set, so I am training with the validation set instead. 

Any suggestions on how to solve?  Thanks.

**Comment by LiZimo** [comment]
Just to expand a little:

It seems "inputs" has rank 3 with the default settings:

```
>>> inputs.get_shape()
TensorShape([Dimension(32), Dimension(2048), Dimension(3)])
```

However, the call to conv2d wants the input rank to be 2 + input_rank.

**Comment by TonythePlaneswalker** [comment]
It is likely a TF version issue. I am using [this conv2d layer](https://www.tensorflow.org/versions/r1.4/api_docs/python/tf/contrib/layers/conv2d) which works for N-D convolution where 1<=N<=3.

To solve this, you can pad the input with tf.expand_dims. No need to upgrade Tensorflow.

**Comment by LiZimo** [comment]
I see.  Does it matter which axis to expand, as long as it's not the first one?

**Comment by TonythePlaneswalker** [comment]
And not the last one
