### ISSUE TITLE
Some issue during training

### ISSUE THREAD

**Issue by powenlo** [TonythePlaneswalker/pcn#12]
Hey, I would like to ask for some help on this issue. When I do the training on my own dataset, some problems come up in the middle of the training and stop the training process, the terminal shows as follows:

Process _Worker-7:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/ying/.local/lib/python3.5/site-packages/tensorpack/dataflow/parallel.py", line 267, in run
    for dp in self.ds:
  File "/home/ying/Documents/po/pcn-master/data_util.py", line 24, in get_data
    input = resample_pcd(input, self.input_size)
  File "/home/ying/Documents/po/pcn-master/data_util.py", line 12, in resample_pcd
    idx = np.concatenate([idx, np.random.randint(pcd.shape[0], size=n-pcd.shape[0])])
  File "mtrand.pyx", line 993, in mtrand.RandomState.randint
ValueError: low >= high

Does anyone have ideas on this? Any help is welcome.

Look forward to hearing from you guys!!

**Comment by TonythePlaneswalker** [comment]
Looks like you have an empty point cloud, i.e. `pcd.shape[0] == 0`.

**Comment by powenlo** [comment]
Thanks for your help. I will try to look into the issue.
