### ISSUE TITLE
ValueError: Convolution expects input with rank 4, got 3

### ISSUE THREAD

**Issue by ChangMingCS** [TonythePlaneswalker/pcn#17]
Hello,
when i run the demo.py, there is an error occured:
`Traceback (most recent call last):
  File "demo.py", line 32, in <module>
    model = model_module.Model(inputs, gt, tf.constant(1.0))
  File "/home/rjjh/tensorflow/pcn-master/models/pcn_cd.py", line 12, in __init__
    self.features = self.create_encoder(inputs)
  File "/home/rjjh/tensorflow/pcn-master/models/pcn_cd.py", line 21, in create_encoder
    features = mlp_conv(inputs, [128, 256])
  File "/home/rjjh/tensorflow/pcn-master/tf_util.py", line 28, in mlp_conv
    scope='conv_%d' % i)
  File "/home/rjjh/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/rjjh/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1154, in convolution2d
    conv_dims=2)
  File "/home/rjjh/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/rjjh/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1025, in convolution
    (conv_dims + 2, input_rank))
ValueError: Convolution expects input with rank 4, got 3`
why it comes and how can i fix it? thank you.

**Comment by TonythePlaneswalker** [comment]
Try changing `tf.contrib.layers.conv2d` in `tf_util.py` to `tf.contrib.layers.conv1d`.

**Comment by TonythePlaneswalker** [comment]
First, `tf.contrib.layers.conv1d` does exist. See the [documentation](https://www.tensorflow.org/api_docs/python/tf/contrib/layers/conv1d). `tf.layers.conv1d` also works. You just need to separate the batch norm layer from the conv layer.

**Comment by ChangMingCS** [comment]
OK, thank you a lot. I changed the code and the ckpt does not work, I'm trying train the pcn again.
