### ISSUE TITLE
Unable to run demo

### ISSUE THREAD

**Issue by kvmanohar22** [TonythePlaneswalker/pcn#24]
Hi, 

I am having trouble in running the `demo.py` to just check if everything is okay. I keep running into problems with the following error.

System specs:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
```
Tensorflow: 1.12.0, cuda 9.0, python 3.5.

When I run the demo.py script; I get the following error; 

```bash
Traceback (most recent call last):
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1628, in 
_create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes must be equal rank, but are 2 and 0
        From merging shape 1 with other shapes. for 'encoder_0/Tile/multiples_1' (op: 'Pack') with input shapes: [], [1
6384,3], [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", lin
e 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1146, in 
internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 971, in _
autopacking_conversion_function
    return _autopacking_helper(v, dtype, name or "packed")
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 923, in _
autopacking_helper
    return gen_array_ops.pack(elems_as_tensors, name=scope)
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4875,
 in pack
    "Pack", values=values, axis=axis, name=name)
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", lin
e 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 488, i
n new_func
    return func(*args, **kwargs)
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3274, in 
create_op
    op_def=op_def)
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1792, in 
__init__
    control_input_ops)
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1631, in 
_create_c_op
    raise ValueError(str(e))
ValueError: Shapes must be equal rank, but are 2 and 0
        From merging shape 1 with other shapes. for 'encoder_0/Tile/multiples_1' (op: 'Pack') with input shapes: [], [1
6384,3], [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1628, in 
_create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes must be equal rank, but are 2 and 0
        From merging shape 1 with other shapes. for 'encoder_0/Tile/packed' (op: 'Pack') with input shapes: [], [16384,
3], [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", lin
e 524, in _apply_op_helper
    values, as_ref=input_arg.is_ref).dtype.name
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1146, in 
internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 971, in _
autopacking_conversion_function
    return _autopacking_helper(v, dtype, name or "packed")
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 923, in _
autopacking_helper
    return gen_array_ops.pack(elems_as_tensors, name=scope)
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4875,
 in pack
    "Pack", values=values, axis=axis, name=name)
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", lin
e 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 488, i
n new_func
    return func(*args, **kwargs)
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3274, in 
create_op
    op_def=op_def)
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1792, in 
__init__
    control_input_ops)
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1631, in 
_create_c_op
    raise ValueError(str(e))
ValueError: Shapes must be equal rank, but are 2 and 0
        From merging shape 1 with other shapes. for 'encoder_0/Tile/packed' (op: 'Pack') with input shapes: [], [16384,
3], [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 35, in <module>
    model = model_module.Model(inputs, gt, tf.constant(1.0), 0.5)
  File "/home/ankush/kv/pcn/models/pcn_cd.py", line 13, in __init__
    self.features = self.create_encoder(inputs, npts)
  File "/home/ankush/kv/pcn/models/pcn_cd.py", line 28, in create_encoder
    features_global = point_unpool(point_maxpool(features, npts, keepdims=True), npts)
  File "/home/ankush/kv/pcn/tf_util.py", line 48, in point_unpool
    outputs = [tf.tile(f, [1, npts[i], 1]) for i,f in enumerate(inputs)]
  File "/home/ankush/kv/pcn/tf_util.py", line 48, in <listcomp>
    outputs = [tf.tile(f, [1, npts[i], 1]) for i,f in enumerate(inputs)]
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8805,
 in tile
    "Tile", input=input, multiples=multiples, name=name)
  File "/home/ankush/anaconda3/envs/pcn/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", lin
e 528, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'multiples' to a tensor and failed. Error: Shapes must be equal rank, but are 2 and 0
        From merging shape 1 with other shapes. for 'encoder_0/Tile/packed' (op: 'Pack') with input shapes: [], [16384,
3], [].
```
I did check the inputs and they do not seem to be of 0 rank. Quite surprising. Could you please have a look at this?

Thanks!

**Comment by kvmanohar22** [comment]
Fixed this in #25. 

Closing it here.
