### ISSUE TITLE
Error when rendering

### ISSUE THREAD

**Issue by BlankCheng** [TonythePlaneswalker/pcn#28]
Hello.
I come across an error when trying to render a single view point cloud using render_depth.py in ./render.

`../shapenet_v1/ShapeNetCore.v1/04530566/f1800fb3a9873af1e64f09105f9c8a56/model.obj
Traceback (most recent call last):
  File "/snap/blender/20/2.79/scripts/addons/io_scene_obj/__init__.py", line 148, in execute
    return import_obj.load(context, **keywords)
  File "/snap/blender/20/2.79/scripts/addons/io_scene_obj/import_obj.py", line 1096, in load
    idx = int(obj_vert[0]) - 1
ValueError: invalid literal for int() with base 10: b'8f'

location: /snap/blender/20/2.79/scripts/modules/bpy/ops.py:189

location: /snap/blender/20/2.79/scripts/modules/bpy/ops.py:189
Traceback (most recent call last):
  File "/snap/blender/20/2.79/scripts/addons/io_scene_obj/__init__.py", line 148, in execute
    return import_obj.load(context, **keywords)
  File "/snap/blender/20/2.79/scripts/addons/io_scene_obj/import_obj.py", line 1096, in load
    idx = int(obj_vert[0]) - 1
ValueError: invalid literal for int() with base 10: b'f'

location: /snap/blender/20/2.79/scripts/modules/bpy/ops.py:189

location: /snap/blender/20/2.79/scripts/modules/bpy/ops.py:189
Traceback (most recent call last):
  File "/snap/blender/20/2.79/scripts/addons/io_scene_obj/__init__.py", line 148, in execute
    return import_obj.load(context, **keywords)
  File "/snap/blender/20/2.79/scripts/addons/io_scene_obj/import_obj.py", line 1096, in load
    idx = int(obj_vert[0]) - 1
ValueError: invalid literal for int() with base 10: b'20.646'

location: /snap/blender/20/2.79/scripts/modules/bpy/ops.py:189

location: /snap/blender/20/2.79/scripts/modules/bpy/ops.py:189
`
I use blender 2.79, do I need to update or do something?
It renders successfully first 6 .obj, and fails from then on.

Best 
Cheng

**Comment by TonythePlaneswalker** [comment]
Looks like there is a problem with the obj file. There's a float value where an int is expected. You can skip these files if there are not too many of them.

**Comment by BlankCheng** [comment]
Thanks! I'll try it. 
I'm closing this issue.
